services:
  - type: web
    name: library-system-backend
    runtime: docker
    rootDir: library-system/backend
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /v3/api-docs
